// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package order

import (
	"context"

	"infar/services/order/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateReq       = pb.CreateReq
	DeleteReq       = pb.DeleteReq
	GetReq          = pb.GetReq
	ListReq         = pb.ListReq
	ListResponse    = pb.ListResponse
	Response        = pb.Response
	UpdateReq       = pb.UpdateReq
	UpdateStatusReq = pb.UpdateStatusReq

	Order interface {
		// 1. 新增
		Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Response, error)
		// 2. 更新
		Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*Response, error)
		// 3. 刪除
		Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Response, error)
		// 4. 取得單筆
		Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*Response, error)
		// 5. 分頁列表
		List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResponse, error)
		// 6. 狀態切換
		UpdateStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*Response, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

// 1. 新增
func (m *defaultOrder) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

// 2. 更新
func (m *defaultOrder) Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}

// 3. 刪除
func (m *defaultOrder) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.Delete(ctx, in, opts...)
}

// 4. 取得單筆
func (m *defaultOrder) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.Get(ctx, in, opts...)
}

// 5. 分頁列表
func (m *defaultOrder) List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResponse, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

// 6. 狀態切換
func (m *defaultOrder) UpdateStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.UpdateStatus(ctx, in, opts...)
}
