apiVersion: v1
kind: ConfigMap
metadata:
  name: order-api-conf
  namespace: app
data:
  order-api.yaml: |
    Name: order-api
    Host: 0.0.0.0
    Port: 8889
    Auth:
      AccessSecret: infar-secret-2026
      AccessExpire: 86400
    OrderRpc:
      Endpoints:
        - order-rpc-svc.app.svc.cluster.local:9090
    UserRpc:
      Endpoints:
        - user-rpc-svc.app.svc.cluster.local:9090
    # 🚀 補上 Kafka 內網位址
    KqPusherConf:
      Brokers:
        - kafka-service.infra.svc.cluster.local:9092
      Topic: order-create
    # 🚀 補上 Redis 內網位址
    Redis:
      Host: redis-master.infra.svc.cluster.local:6379
      Type: node
      Pass: InfarDbPass123

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: app
  labels:
    app: order-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
      annotations:
        infar.io/config-last-updated: "20260411" # 👈 更新戳記，強制重啟 Pod
    spec:
      containers:
      - name: order-api
        image: babyandy0111/infar-order-api:v1
        imagePullPolicy: Always # 👈 強制重新拉取
        ports:
        - containerPort: 8889
        volumeMounts:
        - name: config
          mountPath: /app/etc
      volumes:
      - name: config
        configMap:
          name: order-api-conf

---
apiVersion: v1
kind: Service
metadata:
  name: order-api-svc
  namespace: app
spec:
  ports:
  - port: 8889
    targetPort: 8889
  selector:
    app: order-api
