apiVersion: v1
kind: ConfigMap
metadata:
  name: user-api-conf
  namespace: app
data:
  user-api.yaml: |
    Name: user-api
    Host: 0.0.0.0
    Port: 8888
    UserRpc:
      Endpoints:
        - user-rpc-svc.app.svc.cluster.local:9090
    Auth:
      AccessSecret: infar-secret-2026
      AccessExpire: 86400

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
      annotations:
        infar.io/config-last-updated: "2026-04-06-2315"
    spec:
      containers:
      - name: user-api
        image: babyandy0111/infar-user-api:v1
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: config
          mountPath: /app/etc
      volumes:
      - name: config
        configMap:
          name: user-api-conf

---
apiVersion: v1
kind: Service
metadata:
  name: user-api-svc
  namespace: app
spec:
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: user-api
