apiVersion: v1
kind: ConfigMap
metadata:
  name: order-rpc-conf
  namespace: app
data:
  order-rpc.yaml: |
    Name: order-rpc
    ListenOn: 0.0.0.0:9091
    DataSource: host=postgres.infra.svc.cluster.local port=5432 user=infar_admin password=InfarDbPass123 dbname=infar_db sslmode=disable
    CacheRedis:
      - Host: redis-master.infra.svc.cluster.local:6379
        Pass: InfarDbPass123
        Type: node

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-rpc
  namespace: app
  labels:
    app: order-rpc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-rpc
  template:
    metadata:
      labels:
        app: order-rpc
      annotations:
        infar.io/config-last-updated: "20260406"
    spec:
      containers:
      - name: order-rpc
        image: babyandy0111/infar-order-rpc:v1
        ports:
        - containerPort: 9091
        volumeMounts:
        - name: config
          mountPath: /app/etc
      volumes:
      - name: config
        configMap:
          name: order-rpc-conf

---
apiVersion: v1
kind: Service
metadata:
  name: order-rpc-svc
  namespace: app
spec:
  ports:
  - port: 9091
    targetPort: 9091
  selector:
    app: order-rpc
