// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type LoginReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
	Provider string `json:"provider,default=email"`
}

type LoginRes struct {
	Id    int64  `json:"id"`
	Token string `json:"token"`
}

type RegisterReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
	Provider string `json:"provider,options=email|phone|google|github|line"`
}

type RegisterRes struct {
	Id int64 `json:"id"`
}

type UserInfoReq struct {
	Id int64 `json:"id,optional"` // 可從 JWT 獲取，不強制要求傳入
}

type UserInfoRes struct {
	Id       int64    `json:"id"`
	Account  string   `json:"account"`
	Provider string   `json:"provider"`
	Roles    []string `json:"roles"`
	Nickname string   `json:"nickname"`
	Name     string   `json:"name"`
	Age      int32    `json:"age"`
	Phone    string   `json:"phone"`
	Address  string   `json:"address"`
}
