// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userProfilesFieldNames          = builder.RawFieldNames(&UserProfiles{}, true)
	userProfilesRows                = strings.Join(userProfilesFieldNames, ",")
	userProfilesRowsExpectAutoSet   = strings.Join(stringx.Remove(userProfilesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	userProfilesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(userProfilesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicUserProfilesIdPrefix     = "cache:public:userProfiles:id:"
	cachePublicUserProfilesUserIdPrefix = "cache:public:userProfiles:userId:"
)

type (
	userProfilesModel interface {
		Insert(ctx context.Context, data *UserProfiles) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserProfiles, error)
		FindOneByUserId(ctx context.Context, userId int64) (*UserProfiles, error)
		Update(ctx context.Context, data *UserProfiles) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserProfilesModel struct {
		sqlc.CachedConn
		table string
	}

	UserProfiles struct {
		Id        int64          `db:"id"`         // 流水號
		UserId    int64          `db:"user_id"`    // 關聯用戶 ID
		Nickname  sql.NullString `db:"nickname"`   // 暱稱
		Name      sql.NullString `db:"name"`       // 真實姓名
		Age       sql.NullInt64  `db:"age"`        // 年齡
		Phone     sql.NullString `db:"phone"`      // 聯絡電話
		Address   sql.NullString `db:"address"`    // 住址
		Avatar    sql.NullString `db:"avatar"`     // 頭像 URL
		CreatedAt time.Time      `db:"created_at"` // 資料建立時間
		UpdatedAt sql.NullTime   `db:"updated_at"` // 資料更新時間
	}
)

func newUserProfilesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserProfilesModel {
	return &defaultUserProfilesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."user_profiles"`,
	}
}

func (m *defaultUserProfilesModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	publicUserProfilesIdKey := fmt.Sprintf("%s%v", cachePublicUserProfilesIdPrefix, id)
	publicUserProfilesUserIdKey := fmt.Sprintf("%s%v", cachePublicUserProfilesUserIdPrefix, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicUserProfilesIdKey, publicUserProfilesUserIdKey)
	return err
}

func (m *defaultUserProfilesModel) FindOne(ctx context.Context, id int64) (*UserProfiles, error) {
	publicUserProfilesIdKey := fmt.Sprintf("%s%v", cachePublicUserProfilesIdPrefix, id)
	var resp UserProfiles
	err := m.QueryRowCtx(ctx, &resp, publicUserProfilesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", userProfilesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserProfilesModel) FindOneByUserId(ctx context.Context, userId int64) (*UserProfiles, error) {
	publicUserProfilesUserIdKey := fmt.Sprintf("%s%v", cachePublicUserProfilesUserIdPrefix, userId)
	var resp UserProfiles
	err := m.QueryRowIndexCtx(ctx, &resp, publicUserProfilesUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where user_id = $1 limit 1", userProfilesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserProfilesModel) Insert(ctx context.Context, data *UserProfiles) (sql.Result, error) {
	publicUserProfilesIdKey := fmt.Sprintf("%s%v", cachePublicUserProfilesIdPrefix, data.Id)
	publicUserProfilesUserIdKey := fmt.Sprintf("%s%v", cachePublicUserProfilesUserIdPrefix, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7)", m.table, userProfilesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Nickname, data.Name, data.Age, data.Phone, data.Address, data.Avatar)
	}, publicUserProfilesIdKey, publicUserProfilesUserIdKey)
	return ret, err
}

func (m *defaultUserProfilesModel) Update(ctx context.Context, newData *UserProfiles) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	publicUserProfilesIdKey := fmt.Sprintf("%s%v", cachePublicUserProfilesIdPrefix, data.Id)
	publicUserProfilesUserIdKey := fmt.Sprintf("%s%v", cachePublicUserProfilesUserIdPrefix, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, userProfilesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.Nickname, newData.Name, newData.Age, newData.Phone, newData.Address, newData.Avatar)
	}, publicUserProfilesIdKey, publicUserProfilesUserIdKey)
	return err
}

func (m *defaultUserProfilesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicUserProfilesIdPrefix, primary)
}

func (m *defaultUserProfilesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", userProfilesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserProfilesModel) tableName() string {
	return m.table
}
