// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userRolesFieldNames          = builder.RawFieldNames(&UserRoles{}, true)
	userRolesRows                = strings.Join(userRolesFieldNames, ",")
	userRolesRowsExpectAutoSet   = strings.Join(stringx.Remove(userRolesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	userRolesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(userRolesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cachePublicUserRolesIdPrefix           = "cache:public:userRoles:id:"
	cachePublicUserRolesUserIdRoleIdPrefix = "cache:public:userRoles:userId:roleId:"
)

type (
	userRolesModel interface {
		Insert(ctx context.Context, data *UserRoles) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserRoles, error)
		FindOneByUserIdRoleId(ctx context.Context, userId int64, roleId int64) (*UserRoles, error)
		Update(ctx context.Context, data *UserRoles) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserRolesModel struct {
		sqlc.CachedConn
		table string
	}

	UserRoles struct {
		Id        int64        `db:"id"`         // 流水號
		UserId    int64        `db:"user_id"`    // 用戶流水號
		RoleId    int64        `db:"role_id"`    // 角色流水號
		CreatedAt time.Time    `db:"created_at"` // 資料建立時間 @type=auto_createdtime
		UpdatedAt sql.NullTime `db:"updated_at"` // 資料更新時間 @type=auto_updatedtime
	}
)

func newUserRolesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserRolesModel {
	return &defaultUserRolesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"public"."user_roles"`,
	}
}

func (m *defaultUserRolesModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	publicUserRolesIdKey := fmt.Sprintf("%s%v", cachePublicUserRolesIdPrefix, id)
	publicUserRolesUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cachePublicUserRolesUserIdRoleIdPrefix, data.UserId, data.RoleId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicUserRolesIdKey, publicUserRolesUserIdRoleIdKey)
	return err
}

func (m *defaultUserRolesModel) FindOne(ctx context.Context, id int64) (*UserRoles, error) {
	publicUserRolesIdKey := fmt.Sprintf("%s%v", cachePublicUserRolesIdPrefix, id)
	var resp UserRoles
	err := m.QueryRowCtx(ctx, &resp, publicUserRolesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", userRolesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRolesModel) FindOneByUserIdRoleId(ctx context.Context, userId int64, roleId int64) (*UserRoles, error) {
	publicUserRolesUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cachePublicUserRolesUserIdRoleIdPrefix, userId, roleId)
	var resp UserRoles
	err := m.QueryRowIndexCtx(ctx, &resp, publicUserRolesUserIdRoleIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where user_id = $1 and role_id = $2 limit 1", userRolesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, roleId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRolesModel) Insert(ctx context.Context, data *UserRoles) (sql.Result, error) {
	publicUserRolesIdKey := fmt.Sprintf("%s%v", cachePublicUserRolesIdPrefix, data.Id)
	publicUserRolesUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cachePublicUserRolesUserIdRoleIdPrefix, data.UserId, data.RoleId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2)", m.table, userRolesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.RoleId)
	}, publicUserRolesIdKey, publicUserRolesUserIdRoleIdKey)
	return ret, err
}

func (m *defaultUserRolesModel) Update(ctx context.Context, newData *UserRoles) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	publicUserRolesIdKey := fmt.Sprintf("%s%v", cachePublicUserRolesIdPrefix, data.Id)
	publicUserRolesUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cachePublicUserRolesUserIdRoleIdPrefix, data.UserId, data.RoleId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, userRolesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.RoleId)
	}, publicUserRolesIdKey, publicUserRolesUserIdRoleIdKey)
	return err
}

func (m *defaultUserRolesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePublicUserRolesIdPrefix, primary)
}

func (m *defaultUserRolesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", userRolesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserRolesModel) tableName() string {
	return m.table
}
