// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateReq struct {
	UserId  int32   `json:"user_id"`
	OrderNo string  `json:"order_no"`
	Amount  float64 `json:"amount"`
	Status  string  `json:"status"`
}

type DeleteReq struct {
	Id int64 `path:"id"`
}

type GetReq struct {
	Id int64 `path:"id"`
}

type ListReq struct {
	Page     int64  `form:"page,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Keyword  string `form:"keyword,optional"`
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type UpdateReq struct {
	Id      int64   `json:"id"`
	UserId  int32   `json:"user_id"`
	OrderNo string  `json:"order_no"`
	Amount  float64 `json:"amount"`
	Status  string  `json:"status"`
}

type UpdateStatusReq struct {
	Id     int64 `json:"id"`
	Status int64 `json:"status"`
}
