apiVersion: v1
kind: ConfigMap
metadata:
  name: user-rpc-conf
  namespace: app
data:
  user.yaml: |
    Name: user.rpc
    ListenOn: 0.0.0.0:9090
    DataSource: host=postgres.infra.svc.cluster.local port=5432 user=infar_admin password=InfarDbPass123 dbname=infar_db sslmode=disable
    CacheRedis:
      - Host: redis-master.infra.svc.cluster.local:6379
        Pass: InfarDbPass123
        Type: node

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-rpc
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-rpc
  template:
    metadata:
      labels:
        app: user-rpc
      annotations:
        infar.io/config-last-updated: "2026-04-06-2315" # 👈 改這裡就會自動重啟
    spec:
      containers:
      - name: user-rpc
        image: babyandy0111/infar-user-rpc:v1
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /app/etc
      volumes:
      - name: config
        configMap:
          name: user-rpc-conf

---
apiVersion: v1
kind: Service
metadata:
  name: user-rpc-svc
  namespace: app
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: user-rpc
