server {
    listen 80;

    # 靜態網頁與 SPA 路由
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 將 /user 開頭的請求轉發給 K8s 內的 user-api 服務
    location /user/ {
        proxy_pass http://user-api-svc.app.svc.cluster.local:8888/user/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 將 /v1/order 開頭的請求轉發給 K8s 內的 order-api 服務
    location /v1/order/ {
        proxy_pass http://order-api-svc.app.svc.cluster.local:8889/v1/order/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
